fix

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -4,10 +4,12 @@ on:
   push:
     tags:
       - "v*"
+    branches:
+      - main
   workflow_dispatch:
 
 permissions:
-  contents: read
+  contents: write
   packages: write
 
 env:
@@ -19,6 +21,7 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
 
@@ -32,6 +35,38 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Get current version
+        id: get_version
+        run: |
+          # Get the latest tag
+          latest_tag=$(git describe --tags --abbrev=0)
+          echo "Latest tag: $latest_tag"
+
+          # Extract the patch version and increment it
+          version_regex="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
+          if [[ "$latest_tag" =~ $version_regex ]]; then
+            major="${BASH_REMATCH[1]}"
+            minor="${BASH_REMATCH[2]}"
+            patch="${BASH_REMATCH[3]}"
+            new_patch=$((patch + 1))
+            new_tag="v${major}.${minor}.${new_patch}"
+            echo "New tag: $new_tag"
+            echo "new_tag=$new_tag" >> $GITHUB_ENV
+          else
+            echo "Invalid version format in the latest tag."
+            exit 1
+          fi
+
+      - name: Create new tag
+        if: github.event.pull_request.merged == true
+        run: |
+          git config user.name "GitHub Actions"
+          git config user.email "actions@github.com"
+
+          # Create and push the new tag
+          git tag ${{ env.new_tag }}
+          git push origin ${{ env.new_tag }}
+
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
@@ -40,4 +75,6 @@ jobs:
           push: true
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          tags: ${{env.REGISTRY}}/${{ github.repository }}:${{ github.ref_name }}
+          tags: |
+            ${{env.REGISTRY}}/${{ github.repository }}:${{ env.new_tag }}
+            ${{env.REGISTRY}}/${{ github.repository }}:latest
